export default {
  appName: 'CHMPST',
  screenName: {
    splash: 'CMSplashScreen',
    register: 'CMRegisterScreen',
    login: 'CMLoginScreen',
    main: 'CMMainScreen',
    settings: 'CMSettingsScreen',
    editProfile: 'CMEditProfileScreen',
    editTeam: 'CMEditTeamScreen',
    league: 'CMLeagueScreen',
    editLeague: 'CMEditLeagueScreen',
    leagueSettings: 'CMLeagueSettingsScreen',
    seasonHistory: 'CMSeasonHistoryScreen',
    seasonSchedule: 'CMSeasonScheduleScreen',
    generateSchedule: 'CMGenerateScheduleScreen',
    changePwd: 'CMChangePwdScreen',
    leagueDetails: 'CMLeagueDetailsScreen',
    players: 'CMPlayersScreen',
    playerDetails: 'CMPlayerDetailsScreen',
    playersOfTeam: 'CMPlayersOfTeamScreen',
    editPlayer: 'CMEditPlayerScreen',
    editPlayerStats: 'CMEditPlayerStatsScreen',
    editEvent: 'CMEditEventScreen',
    editMatch: 'CMEditMatchScreen',
    scoreboard: 'CMScoreboardScreen',
    teamManagement: 'CMTeamManagementScreen',
    teamManagementTab: 'CMTeamManagementTabScreen',
    recruitPlayers: 'CMRecruitPlayersScreen',
    myPlayers: 'CMMyPlayersScreen',
    playerInvites: 'CMPlayerInvitesScreen',
    playerClaims: 'CMPlayerClaimsScreen',
    matchPlayersStats: 'CMMatchPlayersStatsScreen',
    playoffBracket: 'CMPlayoffBracketScreen',
    playoffSchedule: 'CMPlayoffScheduleScreen',
    seasonComplete: 'CMSeasonCompleteScreen',
    newsDetail: 'CMNewsDetailScreen',
    paywall: 'CMPaywallScreen',
  },
  activityType: {
    event: 'event',
    match: 'match',
  },
  gameStatus: {
    notStarted: 'not_started',
    inProgress: 'in_progress',
    finished: 'finished',
    paused: 'paused',
  },
  statType: {
    points: 'points',
    rebounds: 'rebounds',
    fouls: 'fouls',
    assists: 'assists',
    blocks: 'blocks',
    turnovers: 'turnovers',
    steals: 'steals',
  },
  shotType: {
    twoPoint: '2pt',
    threePoint: '3pt',
    freeThrow: 'ft',
  },
  shotResult: {
    made: 'made',
    missed: 'missed',
  },
  reboundType: {
    offensive: 'offensive',
    defensive: 'defensive',
  },
  foulType: {
    committed: 'committed',
    forced: 'forced',
  },
  space: {
    large: 50,
    normal: 30,
    small: 20,
    smallEx: 10,
  },
  radius: {
    smallEx: 8,
    small: 10,
    normal: 16,
  },
  color: {
    white: '#ffffff',
    semiLightGrey: '#A4A4A4',
    lightGrey: '#D4D4D4',
    lightGrey1: '#EAEAEA',
    lightGrey2: '#F5F5F5',
    black: '#000000',
    semiDarkGrey: '#222222',
    denim: '#0C5FB1',
    grey: '#555555',
    darkGrey: '#080808',
    darkGrey2: '#0f0d0d', //161212
    darkGrey3: '#2A2A2A',
    red: '#ff0000',
    orange: '#FF8C00',
    yellow: '#FFD700',
    green: '#00FF88',
    greenAccent: '#00D976',
    greenDark: '#00B866',
    alphaBlack: 'rgba(0, 0, 0, 0.7)',
    alphaBlack1: 'rgba(0, 0, 0, 0.1)',
    alphaModal: 'rgba(0, 0, 0, 0.3)',
    fireBrick: '#A51316',
    darkCerulean: '#0B5B9E',
    gold: '#FFD700',
    silver: '#C0C0C0',
    bronze: '#CD7F32',
    transparent: 'transparent',
  },
  height: {
    textInput: 44,
    iconSmall: 12,
    icon: 20,
    iconBig: 26,
    iconBigEx: 32,
    buttonNormal: 44,
    buttonSmall: 30,
    navBar: 80,
  },
  themeMode: {
    dark: 'dark',
    light: 'light',
  },
  font: {
    regular: 'FamiljenGrotesk-Regular',
    semiBold: 'FamiljenGrotesk-SemiBold',
    bold: 'FamiljenGrotesk-Bold',
    italic: 'FamiljenGrotesk-Italic',
    semiBoldItalic: 'FamiljenGrotesk-SemiBoldItalic',
    boldItalic: 'FamiljenGrotesk-BoldItalic',
  },
  fontSize: {
    smallEx: 12,
    small: 14,
    normal: 16,
    medium: 18,
    large: 20,
    largeEx: 24,
  },
  string: {
    minBirthDate: '1950-01-01T00:00:00',
    initialBirthDate: '2000-01-01T00:00:00',
    ok: 'OK',
    cancel: 'Cancel',
    yes: 'Yes',
    enterYourName: 'Please enter your name.',
    enterTeamName: 'Please enter team name.',
    enterEventName: 'Please enter event name.',
    enterLeagueName: 'Please enter league name.',
    enterValidEmail: 'Please enter a valid email address.',
  },
  playerPosition: {
    pointGuard: 'Point Guard',
    shootingGuard: 'Shooting Guard',
    smallForward: 'Small Forward',
    powerForward: 'Power Forward',
    center: 'Center',
  },
  collectionName: {
    league: 'league',
    playerStats: 'playerStats',
    players: 'players',
    playerInvites: 'playerInvites',
    teams: 'teams',
    events: 'events',
    games: 'games',
    gameStats: 'gameStats',
    seasons: 'seasons',
    matches: 'matches',
    news: 'news',
  },
  storeKit: {
    // StoreKit Product IDs - must match App Store Connect configuration
    productIds: {
      core: {
        monthly: 'com.chmpst.subscription.core.monthly',
        annual: 'com.chmpst.subscription.core.annual',
      },
      pro: {
        monthly: 'com.chmpst.subscription.pro.monthly',
        annual: 'com.chmpst.subscription.pro.annual',
      },
      elite: {
        monthly: 'com.chmpst.subscription.elite.monthly',
        annual: 'com.chmpst.subscription.elite.annual',
      },
    },
  },
  api: {
    // Backend API Configuration
    // Uses domain (HTTPS). Legacy: http://3.238.255.151:3000
    baseUrl: 'https://chmp.io',
    version: 'v1',
  },
  legal: {
    privacyPolicyUrl: 'https://chmp.io/privacy.html',
    termsOfUseUrl: 'https://chmp.io/terms.html',
  },
  featureFlags: {
    leagueCreationStage: 'subscription_required', // 'open' | 'subscription_required'
    subscriptionPolicyStage: 'grace_friendly', // 'open' | 'grace_friendly' | 'strict'
    paywallStage: 'apple_purchase', // 'selection_only' | 'apple_purchase'
  },
};
